repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=100]
        exclude: |
          (?x)(
              ^models_app/admin/__init__.py|
              ^models_app/models/__init__.py|
              ^models_app/migrations/
          )


  - repo: https://github.com/asottile/pyupgrade
    rev: v3.11.0
    hooks:
      - id: pyupgrade
