--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Homebrew)
-- Dumped by pg_dump version 14.18 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: answers; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.answers (
    id bigint NOT NULL,
    text text NOT NULL,
    is_correct boolean NOT NULL,
    question_id bigint NOT NULL
);


ALTER TABLE public.answers OWNER TO hey_art_eq;

--
-- Name: answers_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO hey_art_eq;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO hey_art_eq;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO hey_art_eq;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    title character varying(50) NOT NULL
);


ALTER TABLE public.categories OWNER TO hey_art_eq;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO hey_art_eq;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO hey_art_eq;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO hey_art_eq;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO hey_art_eq;

--
-- Name: favorites; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.favorites (
    id bigint NOT NULL,
    test_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.favorites OWNER TO hey_art_eq;

--
-- Name: favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questions; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.questions (
    id bigint NOT NULL,
    text text NOT NULL,
    image character varying(100) NOT NULL,
    "position" integer NOT NULL,
    test_id bigint NOT NULL,
    CONSTRAINT questions_position_check CHECK (("position" >= 0))
);


ALTER TABLE public.questions OWNER TO hey_art_eq;

--
-- Name: questions_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tests; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.tests (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(250) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_published boolean NOT NULL,
    slug character varying(255) NOT NULL,
    cover character varying(100) NOT NULL,
    author_id bigint NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.tests OWNER TO hey_art_eq;

--
-- Name: tests_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.tests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_results; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.user_results (
    id bigint NOT NULL,
    date timestamp with time zone NOT NULL,
    test_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_results OWNER TO hey_art_eq;

--
-- Name: user_results_answers; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.user_results_answers (
    id bigint NOT NULL,
    userresult_id bigint NOT NULL,
    answer_id bigint NOT NULL
);


ALTER TABLE public.user_results_answers OWNER TO hey_art_eq;

--
-- Name: user_results_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.user_results_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_results_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_results_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.user_results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    avatar character varying(100)
);


ALTER TABLE public.users OWNER TO hey_art_eq;

--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_groups OWNER TO hey_art_eq;

--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: hey_art_eq
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_permissions OWNER TO hey_art_eq;

--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: hey_art_eq
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: answers; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.answers (id, text, is_correct, question_id) FROM stdin;
1	Иван Крамской !	t	1
2	Рафаэль	f	1
3	Ян Вермеер	f	1
4	Ян Вермеер	f	2
5	Иероним Босх !	t	2
6	Рафаэль	f	2
7	Рембрандт	f	3
8	Марк Шагал !	t	3
9	Иван Айвазовский	f	3
10	Девушка, собирающая виноград в окрестностях Неаполя	f	4
11	Спящая цыганка	f	4
12	Похищение Прозерпины !	t	4
13	Неизвестная	f	5
14	Страшный суд	f	5
15	Спящая цыганка !	t	5
16	Девятый вал !	t	6
17	Спаситель Мира	f	6
18	Тайная вечеря	f	6
19	Австралия	f	7
20	Канада	f	7
21	США	f	7
22	Россия	t	7
23	Ливия	f	8
24	Ливан !	t	8
25	Боливия	f	8
26	Монако	f	9
27	Панама	f	9
28	Ватикан !	t	9
29	Израиль	f	9
30	графический редактор;	f	10
31	язык программирования; !	t	10
32	операционная система;	f	10
33	текстовый редактор.	f	10
34	только числа;	f	11
35	числа, строки, списки, кортежи, словари; !	t	11
36	только строки;	f	11
37	только списки.	f	11
38	переменная = значение !	t	12
39	define переменная = значение;	f	12
40	variable: значение;	f	12
41	выделить_память переменная = значение.	f	12
42	особый вид переменной;	f	13
43	блок кода, который выполняет определенную задачу и может быть вызван по имени; !	t	13
44	математическая операция;	f	13
45	специальный символ.	f	13
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Пользователь	6	add_user
22	Can change Пользователь	6	change_user
23	Can delete Пользователь	6	delete_user
24	Can view Пользователь	6	view_user
25	Can add Ответы варианты	7	add_answer
26	Can change Ответы варианты	7	change_answer
27	Can delete Ответы варианты	7	delete_answer
28	Can view Ответы варианты	7	view_answer
29	Can add Категория	8	add_category
30	Can change Категория	8	change_category
31	Can delete Категория	8	delete_category
32	Can view Категория	8	view_category
33	Can add Тест	9	add_test
34	Can change Тест	9	change_test
35	Can delete Тест	9	delete_test
36	Can view Тест	9	view_test
37	Can add Результат прохождения	10	add_userresult
38	Can change Результат прохождения	10	change_userresult
39	Can delete Результат прохождения	10	delete_userresult
40	Can view Результат прохождения	10	view_userresult
41	Can add Вопрос	11	add_question
42	Can change Вопрос	11	change_question
43	Can delete Вопрос	11	delete_question
44	Can view Вопрос	11	view_question
45	Can add Избранное	12	add_favorite
46	Can change Избранное	12	change_favorite
47	Can delete Избранное	12	delete_favorite
48	Can view Избранное	12	view_favorite
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.categories (id, title) FROM stdin;
1	🧑‍🎨 Живопись
2	🗺️ География
3	🖥️ Программирование
4	🟰 Математика
5	🪗 Музыка
6	🛰️ Космос
7	⚽ Спорт
8	🧬 Психология
9	🎬 Синематограф
10	🩴 Стиль
11	🔬 Наука
12	🎱 Игры
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-07-08 22:31:04.24172+03	1	🧑‍🎨 Живопись	1	[{"added": {}}]	8	1
2	2025-07-08 22:37:19.603736+03	1	Известные картины	1	[{"added": {}}, {"added": {"name": "\\u0412\\u043e\\u043f\\u0440\\u043e\\u0441", "object": "\\u0410\\u0432\\u0442\\u043e\\u0440 \\u043a\\u0430\\u0440\\u0442\\u0438\\u043d\\u044b"}}, {"added": {"name": "\\u0412\\u043e\\u043f\\u0440\\u043e\\u0441", "object": "\\u041a\\u0442\\u043e \\u0410\\u0432\\u0442\\u043e\\u0440 \\u043a\\u0430\\u0440\\u0442\\u0438\\u043d\\u044b"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0418\\u0432\\u0430\\u043d \\u041a\\u0440\\u0430\\u043c\\u0441\\u043a\\u043e\\u0439 ! - True"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0420\\u0430\\u0444\\u0430\\u044d\\u043b\\u044c - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u042f\\u043d \\u0412\\u0435\\u0440\\u043c\\u0435\\u0435\\u0440 - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u042f\\u043d \\u0412\\u0435\\u0440\\u043c\\u0435\\u0435\\u0440 - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0418\\u0435\\u0440\\u043e\\u043d\\u0438\\u043c \\u0411\\u043e\\u0441\\u0445 ! - True"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0420\\u0430\\u0444\\u0430\\u044d\\u043b\\u044c - False"}}]	9	1
3	2025-07-08 22:38:09.355274+03	1	Известные картины	2	[{"changed": {"fields": ["\\u041e\\u043f\\u0443\\u0431\\u043b\\u0438\\u043a\\u043e\\u0432\\u0430\\u043d\\u043e"]}}]	9	1
4	2025-07-08 22:40:47.909523+03	1	Известные картины	2	[{"added": {"name": "\\u0412\\u043e\\u043f\\u0440\\u043e\\u0441", "object": "\\u0410\\u0432\\u0442\\u043e\\u0440 \\u043a\\u0430\\u0440\\u0442\\u0438\\u043d\\u044b"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0420\\u0435\\u043c\\u0431\\u0440\\u0430\\u043d\\u0434\\u0442 - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u041c\\u0430\\u0440\\u043a \\u0428\\u0430\\u0433\\u0430\\u043b ! - True"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0418\\u0432\\u0430\\u043d \\u0410\\u0439\\u0432\\u0430\\u0437\\u043e\\u0432\\u0441\\u043a\\u0438\\u0439 - False"}}]	9	1
5	2025-07-08 22:52:48.919548+03	2	Назавание картины	1	[{"added": {}}, {"added": {"name": "\\u0412\\u043e\\u043f\\u0440\\u043e\\u0441", "object": "\\u041a\\u0430\\u043a \\u043d\\u0430\\u0437\\u044b\\u0432\\u0430\\u0435\\u0442\\u0441\\u044f \\u043a\\u0430\\u0440\\u0442\\u0438\\u043d\\u0430"}}, {"added": {"name": "\\u0412\\u043e\\u043f\\u0440\\u043e\\u0441", "object": "\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 \\u043f\\u043e\\u043b\\u043e\\u0442\\u043d\\u0430"}}, {"added": {"name": "\\u0412\\u043e\\u043f\\u0440\\u043e\\u0441", "object": "\\u041a\\u0430\\u043a \\u043d\\u0430\\u0437\\u044b\\u0432\\u0430\\u0435\\u0442\\u0441\\u044f \\u043a\\u0430\\u0440\\u0442\\u0438\\u043d\\u0430"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0414\\u0435\\u0432\\u0443\\u0448\\u043a\\u0430, \\u0441\\u043e\\u0431\\u0438\\u0440\\u0430\\u044e\\u0449\\u0430\\u044f \\u0432\\u0438\\u043d\\u043e\\u0433\\u0440\\u0430\\u0434 \\u0432 \\u043e\\u043a\\u0440\\u0435\\u0441\\u0442\\u043d\\u043e\\u0441\\u0442\\u044f\\u0445 \\u041d\\u0435\\u0430\\u043f\\u043e\\u043b\\u044f - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0421\\u043f\\u044f\\u0449\\u0430\\u044f \\u0446\\u044b\\u0433\\u0430\\u043d\\u043a\\u0430 - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u041f\\u043e\\u0445\\u0438\\u0449\\u0435\\u043d\\u0438\\u0435 \\u041f\\u0440\\u043e\\u0437\\u0435\\u0440\\u043f\\u0438\\u043d\\u044b ! - True"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u041d\\u0435\\u0438\\u0437\\u0432\\u0435\\u0441\\u0442\\u043d\\u0430\\u044f - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0421\\u0442\\u0440\\u0430\\u0448\\u043d\\u044b\\u0439 \\u0441\\u0443\\u0434 - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0421\\u043f\\u044f\\u0449\\u0430\\u044f \\u0446\\u044b\\u0433\\u0430\\u043d\\u043a\\u0430 ! - True"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0414\\u0435\\u0432\\u044f\\u0442\\u044b\\u0439 \\u0432\\u0430\\u043b ! - True"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0421\\u043f\\u0430\\u0441\\u0438\\u0442\\u0435\\u043b\\u044c \\u041c\\u0438\\u0440\\u0430 - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0422\\u0430\\u0439\\u043d\\u0430\\u044f \\u0432\\u0435\\u0447\\u0435\\u0440\\u044f - False"}}]	9	1
6	2025-07-08 22:53:09.7571+03	2	Назавание картины	2	[{"changed": {"fields": ["\\u041e\\u0431\\u043b\\u043e\\u0436\\u043a\\u0430"]}}]	9	1
7	2025-07-08 22:54:49.381587+03	2	🗺️ География	1	[{"added": {}}]	8	1
8	2025-07-08 22:55:49.189672+03	3	Блиц	1	[{"added": {}}]	9	1
9	2025-07-08 23:04:09.213111+03	3	Блиц	2	[{"added": {"name": "\\u0412\\u043e\\u043f\\u0440\\u043e\\u0441", "object": "\\u041a\\u0430\\u043a\\u0430\\u044f \\u0441\\u0442\\u0440\\u0430\\u043d\\u0430 \\u0441\\u0430\\u043c\\u0430\\u044f \\u0431\\u043e\\u043b\\u044c\\u0448\\u0430\\u044f \\u0432 \\u043c\\u0438\\u0440\\u0435?"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0410\\u0432\\u0441\\u0442\\u0440\\u0430\\u043b\\u0438\\u044f - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u041a\\u0430\\u043d\\u0430\\u0434\\u0430 - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0421\\u0428\\u0410 - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0420\\u043e\\u0441\\u0441\\u0438\\u044f - True"}}]	9	1
10	2025-07-08 23:06:46.339948+03	3	Блиц	2	[{"added": {"name": "\\u0412\\u043e\\u043f\\u0440\\u043e\\u0441", "object": "\\u041d\\u0430 \\u0444\\u043b\\u0430\\u0433\\u0435 \\u043a\\u0430\\u043a\\u043e\\u0439 \\u0441\\u0442\\u0440\\u0430\\u043d\\u044b \\u0438\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0451\\u043d \\u043a\\u0435\\u0434\\u0440?"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u041b\\u0438\\u0432\\u0438\\u044f - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u041b\\u0438\\u0432\\u0430\\u043d ! - True"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0411\\u043e\\u043b\\u0438\\u0432\\u0438\\u044f - False"}}]	9	1
11	2025-07-08 23:09:16.375545+03	3	Блиц	2	[{"added": {"name": "\\u0412\\u043e\\u043f\\u0440\\u043e\\u0441", "object": "\\u041a\\u0430\\u043a\\u043e\\u0435 \\u0433\\u043e\\u0441\\u0443\\u0434\\u0430\\u0440\\u0441\\u0442\\u0432\\u043e \\u0441\\u0430\\u043c\\u043e\\u0435 \\u043c\\u0430\\u043b\\u0435\\u043d\\u044c\\u043a\\u043e\\u0435 \\u0432 \\u043c\\u0438\\u0440\\u0435?"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u041c\\u043e\\u043d\\u0430\\u043a\\u043e - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u041f\\u0430\\u043d\\u0430\\u043c\\u0430 - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0412\\u0430\\u0442\\u0438\\u043a\\u0430\\u043d ! - True"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0418\\u0437\\u0440\\u0430\\u0438\\u043b\\u044c - False"}}]	9	1
12	2025-07-08 23:17:29.865757+03	3	🖥️ Программирование	1	[{"added": {}}]	8	1
13	2025-07-08 23:18:45.318345+03	2	Вася	1	[{"added": {}}]	6	1
14	2025-07-08 23:25:13.031753+03	4	Просто Python	1	[{"added": {}}, {"added": {"name": "\\u0412\\u043e\\u043f\\u0440\\u043e\\u0441", "object": "\\u0427\\u0442\\u043e \\u0442\\u0430\\u043a\\u043e\\u0435 Python?"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0433\\u0440\\u0430\\u0444\\u0438\\u0447\\u0435\\u0441\\u043a\\u0438\\u0439 \\u0440\\u0435\\u0434\\u0430\\u043a\\u0442\\u043e\\u0440; - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u044f\\u0437\\u044b\\u043a \\u043f\\u0440\\u043e\\u0433\\u0440\\u0430\\u043c\\u043c\\u0438\\u0440\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f; ! - True"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u043e\\u043f\\u0435\\u0440\\u0430\\u0446\\u0438\\u043e\\u043d\\u043d\\u0430\\u044f \\u0441\\u0438\\u0441\\u0442\\u0435\\u043c\\u0430; - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0442\\u0435\\u043a\\u0441\\u0442\\u043e\\u0432\\u044b\\u0439 \\u0440\\u0435\\u0434\\u0430\\u043a\\u0442\\u043e\\u0440. - False"}}]	9	1
15	2025-07-08 23:28:44.132648+03	4	Просто Python	2	[{"added": {"name": "\\u0412\\u043e\\u043f\\u0440\\u043e\\u0441", "object": "\\u041a\\u0430\\u043a\\u0438\\u0435 \\u043e\\u0441\\u043d\\u043e\\u0432\\u043d\\u044b\\u0435 \\u0442\\u0438\\u043f\\u044b \\u0434\\u0430\\u043d\\u043d\\u044b\\u0445 \\u0435\\u0441\\u0442\\u044c \\u0432 Python?"}}, {"added": {"name": "\\u0412\\u043e\\u043f\\u0440\\u043e\\u0441", "object": "\\u041a\\u0430\\u043a \\u0432 Python \\u043e\\u0431\\u044a\\u044f\\u0432\\u0438\\u0442\\u044c \\u043f\\u0435\\u0440\\u0435\\u043c\\u0435\\u043d\\u043d\\u0443\\u044e?"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0442\\u043e\\u043b\\u044c\\u043a\\u043e \\u0447\\u0438\\u0441\\u043b\\u0430; - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0447\\u0438\\u0441\\u043b\\u0430, \\u0441\\u0442\\u0440\\u043e\\u043a\\u0438, \\u0441\\u043f\\u0438\\u0441\\u043a\\u0438, \\u043a\\u043e\\u0440\\u0442\\u0435\\u0436\\u0438, \\u0441\\u043b\\u043e\\u0432\\u0430\\u0440\\u0438; ! - True"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0442\\u043e\\u043b\\u044c\\u043a\\u043e \\u0441\\u0442\\u0440\\u043e\\u043a\\u0438; - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0442\\u043e\\u043b\\u044c\\u043a\\u043e \\u0441\\u043f\\u0438\\u0441\\u043a\\u0438. - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u043f\\u0435\\u0440\\u0435\\u043c\\u0435\\u043d\\u043d\\u0430\\u044f = \\u0437\\u043d\\u0430\\u0447\\u0435\\u043d\\u0438\\u0435 ! - True"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "define \\u043f\\u0435\\u0440\\u0435\\u043c\\u0435\\u043d\\u043d\\u0430\\u044f = \\u0437\\u043d\\u0430\\u0447\\u0435\\u043d\\u0438\\u0435; - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "variable: \\u0437\\u043d\\u0430\\u0447\\u0435\\u043d\\u0438\\u0435; - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0432\\u044b\\u0434\\u0435\\u043b\\u0438\\u0442\\u044c_\\u043f\\u0430\\u043c\\u044f\\u0442\\u044c \\u043f\\u0435\\u0440\\u0435\\u043c\\u0435\\u043d\\u043d\\u0430\\u044f = \\u0437\\u043d\\u0430\\u0447\\u0435\\u043d\\u0438\\u0435. - False"}}]	9	1
16	2025-07-08 23:31:29.622023+03	4	Просто Python	2	[{"added": {"name": "\\u0412\\u043e\\u043f\\u0440\\u043e\\u0441", "object": "\\u0427\\u0442\\u043e \\u0442\\u0430\\u043a\\u043e\\u0435 \\u0444\\u0443\\u043d\\u043a\\u0446\\u0438\\u044f \\u0432 Python?"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u043e\\u0441\\u043e\\u0431\\u044b\\u0439 \\u0432\\u0438\\u0434 \\u043f\\u0435\\u0440\\u0435\\u043c\\u0435\\u043d\\u043d\\u043e\\u0439; - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0431\\u043b\\u043e\\u043a \\u043a\\u043e\\u0434\\u0430, \\u043a\\u043e\\u0442\\u043e\\u0440\\u044b\\u0439 \\u0432\\u044b\\u043f\\u043e\\u043b\\u043d\\u044f\\u0435\\u0442 \\u043e\\u043f\\u0440\\u0435\\u0434\\u0435\\u043b\\u0435\\u043d\\u043d\\u0443\\u044e \\u0437\\u0430\\u0434\\u0430\\u0447\\u0443 \\u0438 \\u043c\\u043e\\u0436\\u0435\\u0442 \\u0431\\u044b\\u0442\\u044c \\u0432\\u044b\\u0437\\u0432\\u0430\\u043d \\u043f\\u043e \\u0438\\u043c\\u0435\\u043d\\u0438; ! - True"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u043c\\u0430\\u0442\\u0435\\u043c\\u0430\\u0442\\u0438\\u0447\\u0435\\u0441\\u043a\\u0430\\u044f \\u043e\\u043f\\u0435\\u0440\\u0430\\u0446\\u0438\\u044f; - False"}}, {"added": {"name": "\\u041e\\u0442\\u0432\\u0435\\u0442\\u044b \\u0432\\u0430\\u0440\\u0438\\u0430\\u043d\\u0442\\u044b", "object": "\\u0441\\u043f\\u0435\\u0446\\u0438\\u0430\\u043b\\u044c\\u043d\\u044b\\u0439 \\u0441\\u0438\\u043c\\u0432\\u043e\\u043b. - False"}}]	9	1
17	2025-07-08 23:32:53.094663+03	5	Без вопросов	1	[{"added": {}}]	9	1
18	2025-07-08 23:34:25.360888+03	4	🟰 Математика	1	[{"added": {}}]	8	1
19	2025-07-08 23:37:46.812342+03	5	🪗 Музыка	1	[{"added": {}}]	8	1
20	2025-07-08 23:38:57.519706+03	6	🛰️ Космос	1	[{"added": {}}]	8	1
21	2025-07-08 23:59:54.161651+03	7	⚽ Спорт	1	[{"added": {}}]	8	1
22	2025-07-09 00:00:27.253531+03	8	🧬 Психология	1	[{"added": {}}]	8	1
23	2025-07-09 00:01:09.175242+03	9	🎬 Синематограф	1	[{"added": {}}]	8	1
24	2025-07-09 00:01:43.419434+03	10	🩴 Стиль	1	[{"added": {}}]	8	1
25	2025-07-09 00:02:21.822479+03	11	🔬 Наука	1	[{"added": {}}]	8	1
26	2025-07-09 00:03:07.437342+03	12	🎱 Игры	1	[{"added": {}}]	8	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	models_app	user
7	models_app	answer
8	models_app	category
9	models_app	test
10	models_app	userresult
11	models_app	question
12	models_app	favorite
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-07-08 22:22:18.648285+03
2	contenttypes	0002_remove_content_type_name	2025-07-08 22:22:18.654607+03
3	auth	0001_initial	2025-07-08 22:22:18.681061+03
4	auth	0002_alter_permission_name_max_length	2025-07-08 22:22:18.684823+03
5	auth	0003_alter_user_email_max_length	2025-07-08 22:22:18.688517+03
6	auth	0004_alter_user_username_opts	2025-07-08 22:22:18.692016+03
7	auth	0005_alter_user_last_login_null	2025-07-08 22:22:18.695342+03
8	auth	0006_require_contenttypes_0002	2025-07-08 22:22:18.696908+03
9	auth	0007_alter_validators_add_error_messages	2025-07-08 22:22:18.70136+03
10	auth	0008_alter_user_username_max_length	2025-07-08 22:22:18.704822+03
11	auth	0009_alter_user_last_name_max_length	2025-07-08 22:22:18.708132+03
12	auth	0010_alter_group_name_max_length	2025-07-08 22:22:18.713481+03
13	auth	0011_update_proxy_permissions	2025-07-08 22:22:18.717+03
14	auth	0012_alter_user_first_name_max_length	2025-07-08 22:22:18.720582+03
15	models_app	0001_initial	2025-07-08 22:22:18.808188+03
16	admin	0001_initial	2025-07-08 22:22:18.818585+03
17	admin	0002_logentry_remove_auto_add	2025-07-08 22:22:18.823832+03
18	admin	0003_logentry_add_action_flag_choices	2025-07-08 22:22:18.830677+03
19	sessions	0001_initial	2025-07-08 22:22:18.837335+03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
2peg950u7ub5ds7eys2i38mg7m42bfsk	.eJxVjUEOgjAUBe_StSkUCrQu3XuG5n1-kSIWQ8vKeHclYcP2zWTeR8xI2b2RR3EVBfgVYjGloEwsxEU4bHl0W_KrC_wX1Hkj9E8fd8AT4mOR_RLzGkjuijxokveF_Xw73FNgRNp_TVt2BtqibGqlG6Kh1DwwDQATa9_phuuK2WoPwCjdc2cVq4ost9ZX4vsD1mZCHA:1uZFTh:Ho7XvyOzJf3l7HNNclV6FHi_sutax_j9WgBipmhmM8g	2025-07-23 00:03:49.096337+03
\.


--
-- Data for Name: favorites; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.favorites (id, test_id, user_id) FROM stdin;
\.


--
-- Data for Name: questions; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.questions (id, text, image, "position", test_id) FROM stdin;
1	Автор картины	questions/image/2025/07/08/Иван_Крамскои_Неизвестная.jpg	1	1
2	Кто Автор картины	questions/image/2025/07/08/Иероним_Босх_Страшныи_суд.jpg	1	1
3	Автор картины	questions/image/2025/07/08/Марк_Шагал_Над_городом.jpg	1	1
4	Как называется картина	questions/image/2025/07/08/Алессандро_Аллори_Похищение_Прозерпины_.jpg	1	2
5	Название полотна	questions/image/2025/07/08/Анри_Руссо_Спящая_цыганка.jpg	1	2
6	Как называется картина	questions/image/2025/07/08/Иван_Аивазовскии_Девятыи_вал.jpg	1	2
7	Какая страна самая большая в мире?	questions/image/2025/07/08/Какая_страна_самая_большая_в_мире.jpg	1	3
8	На флаге какой страны изображён кедр?	questions/image/2025/07/08/На_флаге_какои_страны_изображен_кедр.jpg	1	3
9	Какое государство самое маленькое в мире?	questions/image/2025/07/08/Какое_государство_самое_маленькое_в_мире.jpg	1	3
10	Что такое Python?	questions/image/2025/07/08/pingv.jpg	1	4
11	Какие основные типы данных есть в Python?	questions/image/2025/07/08/f26db1bd1090d29cbd709540a51d55a5.jpg	1	4
12	Как в Python объявить переменную?	questions/image/2025/07/08/f3a231a16d15a7ae15b5d6b03e70bee5.jpg	1	4
13	Что такое функция в Python?	questions/image/2025/07/08/ed5ec12488f96a1f7e78506f0d0a95cb.jpg	1	4
\.


--
-- Data for Name: tests; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.tests (id, title, description, created_at, updated_at, is_published, slug, cover, author_id, category_id) FROM stdin;
1	Известные картины	Известные картины величайших творцов. Самые знаменитые картины Мира.  Живопись бесконечна, как сама история человечества. Но все же, есть самые великие произведения живописи, которые стали знаковыми для многих эпох и вошли в «золотой фонд» мировых ше	2025-07-08 22:37:19.589508+03	2025-07-08 22:40:47.872666+03	t	izvestnye-kartiny	users/cover/Рафаэль_Сикстинская_мадонна_.jpg	1	1
2	Назавание картины	Определите назавание картины	2025-07-08 22:52:48.898406+03	2025-07-08 22:53:09.71309+03	t	nazavanie-kartiny	users/cover/баиден.png	1	1
3	Блиц	Общие вопросы по географии	2025-07-08 22:55:49.185803+03	2025-07-08 23:09:16.33334+03	t	blits	users/cover/c993c2079e58d91006abfa232235afbb.jpg	1	2
4	Просто Python	несколько простых вопросов по программированию на языке Python	2025-07-08 23:25:13.015177+03	2025-07-08 23:31:29.593281+03	t	prosto-python	users/cover/Spider_dunk.jpeg	2	3
5	Без вопросов	Для теста, без вопросов	2025-07-08 23:32:53.088737+03	2025-07-08 23:32:53.088788+03	t	bez-voprosov	users/cover/e71e2fac8f9d7492cfbc57a0f730adda.jpg	2	3
\.


--
-- Data for Name: user_results; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.user_results (id, date, test_id, user_id) FROM stdin;
1	2025-07-08 22:42:49.572173+03	1	1
2	2025-07-08 23:40:15.276383+03	3	1
3	2025-07-08 23:41:57.84094+03	4	1
4	2025-07-08 23:57:51.39372+03	5	1
\.


--
-- Data for Name: user_results_answers; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.user_results_answers (id, userresult_id, answer_id) FROM stdin;
1	1	8
2	1	1
3	1	6
4	2	25
5	2	19
6	2	28
7	3	33
8	3	37
9	3	45
10	3	38
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.users (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, avatar) FROM stdin;
1	pbkdf2_sha256$600000$kvhHOHEkDI3UI2W5cuHZE5$OowCmVAdeRzPPbbcyhvOvrniwr3KgysnH75rtVx0i/U=	2025-07-08 22:24:00.103857+03	t	art				t	t	2025-07-08 22:23:34.200655+03
2	Vasia123	\N	f	Вася				f	t	2025-07-08 23:18:02+03
\.


--
-- Data for Name: users_groups; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.users_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_permissions; Type: TABLE DATA; Schema: public; Owner: hey_art_eq
--

COPY public.users_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: answers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.answers_id_seq', 45, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.categories_id_seq', 12, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 26, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 12, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: favorites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.favorites_id_seq', 1, false);


--
-- Name: questions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.questions_id_seq', 13, true);


--
-- Name: tests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.tests_id_seq', 5, true);


--
-- Name: user_results_answers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.user_results_answers_id_seq', 10, true);


--
-- Name: user_results_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.user_results_id_seq', 4, true);


--
-- Name: users_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.users_groups_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hey_art_eq
--

SELECT pg_catalog.setval('public.users_user_permissions_id_seq', 1, false);


--
-- Name: answers answers_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT answers_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: categories categories_title_key; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_title_key UNIQUE (title);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: favorites favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_pkey PRIMARY KEY (id);


--
-- Name: favorites favorites_user_id_test_id_d68c5309_uniq; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_user_id_test_id_d68c5309_uniq UNIQUE (user_id, test_id);


--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);


--
-- Name: tests tests_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT tests_pkey PRIMARY KEY (id);


--
-- Name: tests tests_slug_key; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT tests_slug_key UNIQUE (slug);


--
-- Name: user_results_answers user_results_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.user_results_answers
    ADD CONSTRAINT user_results_answers_pkey PRIMARY KEY (id);


--
-- Name: user_results_answers user_results_answers_userresult_id_answer_id_1d31b5de_uniq; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.user_results_answers
    ADD CONSTRAINT user_results_answers_userresult_id_answer_id_1d31b5de_uniq UNIQUE (userresult_id, answer_id);


--
-- Name: user_results user_results_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.user_results
    ADD CONSTRAINT user_results_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: answers_question_id_1c8a95ab; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX answers_question_id_1c8a95ab ON public.answers USING btree (question_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: categories_title_85131203_like; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX categories_title_85131203_like ON public.categories USING btree (title varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: favorites_test_id_25856c59; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX favorites_test_id_25856c59 ON public.favorites USING btree (test_id);


--
-- Name: favorites_user_id_d60eb79f; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX favorites_user_id_d60eb79f ON public.favorites USING btree (user_id);


--
-- Name: questions_test_id_980bebe9; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX questions_test_id_980bebe9 ON public.questions USING btree (test_id);


--
-- Name: tests_author_id_0acb86f2; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX tests_author_id_0acb86f2 ON public.tests USING btree (author_id);


--
-- Name: tests_category_id_cc200afa; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX tests_category_id_cc200afa ON public.tests USING btree (category_id);


--
-- Name: tests_slug_31d27b18_like; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX tests_slug_31d27b18_like ON public.tests USING btree (slug varchar_pattern_ops);


--
-- Name: user_results_answers_answer_id_c1fe2872; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX user_results_answers_answer_id_c1fe2872 ON public.user_results_answers USING btree (answer_id);


--
-- Name: user_results_answers_userresult_id_894c4f27; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX user_results_answers_userresult_id_894c4f27 ON public.user_results_answers USING btree (userresult_id);


--
-- Name: user_results_test_id_9d829160; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX user_results_test_id_9d829160 ON public.user_results USING btree (test_id);


--
-- Name: user_results_user_id_aeb50486; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX user_results_user_id_aeb50486 ON public.user_results USING btree (user_id);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: users_username_e8658fc8_like; Type: INDEX; Schema: public; Owner: hey_art_eq
--

CREATE INDEX users_username_e8658fc8_like ON public.users USING btree (username varchar_pattern_ops);


--
-- Name: answers answers_question_id_1c8a95ab_fk_questions_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT answers_question_id_1c8a95ab_fk_questions_id FOREIGN KEY (question_id) REFERENCES public.questions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: favorites favorites_test_id_25856c59_fk_tests_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_test_id_25856c59_fk_tests_id FOREIGN KEY (test_id) REFERENCES public.tests(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: favorites favorites_user_id_d60eb79f_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_user_id_d60eb79f_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: questions questions_test_id_980bebe9_fk_tests_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_test_id_980bebe9_fk_tests_id FOREIGN KEY (test_id) REFERENCES public.tests(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tests tests_author_id_0acb86f2_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT tests_author_id_0acb86f2_fk_users_id FOREIGN KEY (author_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tests tests_category_id_cc200afa_fk_categories_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT tests_category_id_cc200afa_fk_categories_id FOREIGN KEY (category_id) REFERENCES public.categories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_results_answers user_results_answers_answer_id_c1fe2872_fk_answers_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.user_results_answers
    ADD CONSTRAINT user_results_answers_answer_id_c1fe2872_fk_answers_id FOREIGN KEY (answer_id) REFERENCES public.answers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_results_answers user_results_answers_userresult_id_894c4f27_fk_user_results_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.user_results_answers
    ADD CONSTRAINT user_results_answers_userresult_id_894c4f27_fk_user_results_id FOREIGN KEY (userresult_id) REFERENCES public.user_results(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_results user_results_test_id_9d829160_fk_tests_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.user_results
    ADD CONSTRAINT user_results_test_id_9d829160_fk_tests_id FOREIGN KEY (test_id) REFERENCES public.tests(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_results user_results_user_id_aeb50486_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.user_results
    ADD CONSTRAINT user_results_user_id_aeb50486_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: hey_art_eq
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--
