# Generated by Django 4.2.16 on 2024-12-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "verbose_name": "Ответы варианты",
                "verbose_name_plural": "Ответы варианты",
            },
        ),
        migrations.AlterModelOptions(
            name="userresult",
            options={
                "verbose_name": "Ответ на вопрос",
                "verbose_name_plural": "Ответы на вопросы",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/avatar/", verbose_name="Аватар"
            ),
        ),
    ]
