# Generated by Django 4.2.16 on 2024-12-31 00:28
import os.path

from django.db import migrations, models

from conf.settings.django import BASE_DIR


def fill_cover_for_tests(apps, schema_editor):
    """
    Заполняю все существующие тесты фото-заглушкой
    """
    Test = apps.get_model("models_app", "Test")
    Test.objects.all().update(cover=os.path.join(BASE_DIR, "utils", "data", "pass.jpg"))


class Migration(migrations.Migration):
    dependencies = [
        ("models_app", "0002_alter_answer_options_alter_userresult_options_and_more"),
    ]

    operations = [
        # Добавили поле
        migrations.AddField(
            model_name="test",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/cover/", verbose_name="Обложка"
            ),
        ),
        # Вызываю ф-ю заполнения фото-заглушкой (заполнил)
        migrations.RunPython(fill_cover_for_tests),
        # После заполнения изменю настройки (сделал обязательным)
        migrations.AlterField(
            model_name="test",
            name="cover",
            field=models.ImageField(
                blank=False,
                null=False,
                upload_to="users/cover/",
                verbose_name="Обложка",
            ),
        ),
    ]
