# Generated by Django 4.2.16 on 2025-01-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models_app", "0003_test_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="position",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Позиция в тесте"
            ),
        ),
    ]
