# Generated by Django 4.2.16 on 2025-03-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models_app", "0004_question_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="description",
            field=models.CharField(max_length=250, verbose_name="Описание"),
        ),
    ]
