# Generated by Django 4.2.16 on 2025-05-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models_app", "0005_alter_test_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userresult",
            options={
                "verbose_name": "Результат прохождения",
                "verbose_name_plural": "Результаты прохождения",
            },
        ),
        migrations.AlterField(
            model_name="test",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "test")},
        ),
    ]
